server:
  port: 50000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:mysql://103.74.192.192:3306/boardgame?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: BoardGame
    password: Specialfox233
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        '[format_sql]': false
  flyway:
    enabled: false

# CORS 配置应该通过 WebMvcConfigurer 在代码中配置，而不是在 application.yml 中
# cors:
#   allowed-origins: "http://boardgame.techox.cc,https://boardgame.techox.cc"